
export const CHECK_AUTH = "CHECK_AUTH";
export const CHECK_AUTH_RETURN = "CHECK_AUTH_RETURN";
export const MAKE_LOGIN_REQUEST = "MAKE_LOGIN_REQUEST";
export const MAKE_LOGIN_REQUEST_FAILED = "MAKE_LOGIN_REQUEST_FAILED";
export const MAKE_LOGIN_REQUEST_SUCCESS = "MAKE_LOGIN_REQUEST_SUCCESS";
export const MAKE_LOGIN_REQUEST_RETURN = "MAKE_LOGIN_REQUEST_RETURN";
export const SET_USER = "SET_USER";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_RETURN = "SIGN_UP_RETURN";
export const SUBMIT_STUDY_DETAILS = "SUBMIT_STUDY_DETAILS";
export const SUBMIT_STUDY_DETAILS_RETURN = "SUBMIT_STUDY_DETAILS_RETURN";
export const SUBMIT_COURSES = "SUBMIT_COURSES";
export const SUBMIT_COURSES_RETURN = "SUBMIT_COURSES_RETURN";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_RETURN = "REGISTER_USER_RETURN";
export const DUBLICATE_NUMBER_EMAIL = "DUBLICATE_NUMBER_EMAIL";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const GET_SCHOLARSHIPS = "GET_SCHOLARSHIPS";
export const GET_SCHOLARSHIPS_RETURN = "GET_SCHOLARSHIPS_RETURN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_COMPLETE = "SIGN_OUT_COMPLETE";
export const GET_BLOGS = "GET_BLOGS";
export const GET_BLOGS_RETURN = "GET_BLOGS_RETURN";

export const SET_QUIZ = "SET_QUIZ";
export const SET_QUIZ_DONE = "SET_QUIZ_DONE";
