
export const CHECK_AUTH = "CHECK_AUTH";
export const CHECK_AUTH_RETURN = "CHECK_AUTH_RETURN";
export const MAKE_LOGIN_REQUEST = "MAKE_LOGIN_REQUEST";
export const MAKE_LOGIN_REQUEST_FAILED = "MAKE_LOGIN_REQUEST_FAILED";
export const MAKE_LOGIN_REQUEST_SUCCESS = "MAKE_LOGIN_REQUEST_SUCCESS";
export const MAKE_LOGIN_REQUEST_RETURN = "MAKE_LOGIN_REQUEST_RETURN";
export const SET_USER = "SET_USER";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_RETURN = "SIGN_UP_RETURN";
export const SUBMIT_STUDY_DETAILS = "SUBMIT_STUDY_DETAILS";
export const SUBMIT_STUDY_DETAILS_RETURN = "SUBMIT_STUDY_DETAILS_RETURN";
export const SUBMIT_COURSES = "SUBMIT_COURSES";
export const SUBMIT_COURSES_RETURN = "SUBMIT_COURSES_RETURN";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_RETURN = "REGISTER_USER_RETURN";
export const DUBLICATE_NUMBER_EMAIL = "DUBLICATE_NUMBER_EMAIL";

export const RESET_AUTH_ERROR = "RESET_AUTH_ERROR";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const GET_SCHOLARSHIPS = "GET_SCHOLARSHIPS";
export const GET_SCHOLARSHIPS_RETURN = "GET_SCHOLARSHIPS_RETURN";

export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_COMPLETE = "SIGN_OUT_COMPLETE";

export const GET_BLOGS = "GET_BLOGS";
export const GET_BLOGS_RETURN = "GET_BLOGS_RETURN";

export const SET_QUIZ = "SET_QUIZ";
export const SET_QUIZ_DONE = "SET_QUIZ_DONE";

export const SUBMIT_QUIZ = "SUBMIT_QUIZ";
export const SUBMIT_QUIZ_RETURN = "SUBMIT_QUIZ_RETURN";

export const SHOW_EXPLANATION = "SHOW_EXPLANATION";

export const GET_PREVIOUS_ATTEMPS = "GET_PREVIOUS_ATTEMPS";
export const GET_PREVIOUS_ATTEMPS_RETURN = "GET_PREVIOUS_ATTEMPS_RETURN";


export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_RETURN = "GET_SUBJECTS_RETURN";

export const GET_SUBJECT_DETAILS = "GET_SUBJECT_DETAILS";
export const GET_SUBJECT_DETAILS_RETURN = "GET_SUBJECT_DETAILS_RETURN";

export const GET_PACKAGES = "GET_PACKAGES";
export const GET_PACKAGES_RETURN = "GET_PACKAGES_RETURN";

export const PROCEED_PACKAGES = "PROCEED_PACKAGES";

export const SUBMIT_BUY_PKG = "SUBMIT_BUY_PKG";
export const SUBMIT_BUY_PKG_RETURN = "SUBMIT_BUY_PKG_RETURN";

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
export const GET_ALL_SUBJECTS_RETURN = "GET_ALL_SUBJECTS_RETURN";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_RETURN = "GET_CATEGORIES_RETURN";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORIES_RETURN = "SET_CATEGORIES_RETURN";

export const RESET_SELECTED_PACKAGE = "RESET_SELECTED_PACKAGE";

export const GET_USER = "GET_USER";
export const SET_USER_MYPROFILE = "SET_USER_MYPROFILE";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_RETURN = "EDIT_USER_RETURN";
export const UPDATE_STUDY = "UPDATE_STUDY";
export const UPDATE_STUDY_RETURN = "UPDATE_STUDY_RETURN";



